In [95]:
import pandas as pd
import numpy as np
import os

LOAD DATA

In [96]:
df = pd.read_csv(r"C:\Users\mundl\OneDrive\Documents\data_pipeline\data\raw_books.csv")
df.head()

,title,price,star_rating,availability,category
0,A Light in the Attic,Â£51.77,Three,In stock,All Books
1,Tipping the Velvet,Â£53.74,One,In stock,All Books
2,Soumission,Â£50.10,One,In stock,All Books
3,Sharp Objects,Â£47.82,Four,In stock,All Books
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,All Books

CHECK DATA

In [97]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         100 non-null    str
 1   price         100 non-null    str
 2   star_rating   100 non-null    str
 3   availability  100 non-null    str
 4   category      100 non-null    str
dtypes: str(5)
memory usage: 4.0 KB

In [98]:
df.isnull().sum()

title           0
price           0
star_rating     0
availability    0
category        0
dtype: int64

CHECK DUPLICATES

In [99]:
df.duplicated().sum()

np.int64(0)

In [100]:
df

,title,price,star_rating,availability,category
0,A Light in the Attic,Â£51.77,Three,In stock,All Books
1,Tipping the Velvet,Â£53.74,One,In stock,All Books
2,Soumission,Â£50.10,One,In stock,All Books
3,Sharp Objects,Â£47.82,Four,In stock,All Books
4,Sapiens: A Brief History of Humankind,Â£54.23,Five,In stock,All Books
...,...,...,...,...,...
95,Lumberjanes Vol. 3: A Terrible Plan (Lumberjan...,Â£19.92,Two,In stock,All Books
96,"Layered: Baking, Building, and Styling Spectac...",Â£40.11,One,In stock,All Books
97,Judo: Seven Steps to Black Belt (an Introducto...,Â£53.90,Two,In stock,All Books
98,Join,Â£35.67,Five,In stock,All Books
99,In the Country We Love: My Family Divided,Â£22.00,Four,In stock,All Books

CLEAN PRICE

In [101]:
df["price"] = (
    df["price"].str.replace("Â£","",regex=False)
    .astype(float)
)

In [102]:
df["price"].head()

0    51.77
1    53.74
2    50.10
3    47.82
4    54.23
Name: price, dtype: float64

In [103]:
df.rename(columns = {"price" : "price_gbp"}, inplace = True)

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         100 non-null    str
 1   price_gbp     100 non-null    float64
 2   star_rating   100 non-null    str
 3   availability  100 non-null    str
 4   category      100 non-null    str
dtypes: float64(1), str(4)
memory usage: 4.0 KB

CONVERT RATING

In [105]:
rating = {
    "One" : 1,
    "Two" : 2,
    "Three" : 3,
    "Four" : 4,
    "Five" : 5
}

df["star_rating"] = df["star_rating"].map(rating)

In [106]:
df["star_rating"].head()

0    3
1    1
2    1
3    4
4    5
Name: star_rating, dtype: int64

ADD INR PRICE

In [108]:
GBP_TO_INR = 105
df["price_inr"] = df["price_gbp"] * GBP_TO_INR

In [109]:
df["price_inr"].head()

0    5435.85
1    5642.70
2    5260.50
3    5021.10
4    5694.15
Name: price_inr, dtype: float64

In [110]:
df.head()

,title,price_gbp,star_rating,availability,category,price_inr
0,A Light in the Attic,51.77,3,In stock,All Books,5435.85
1,Tipping the Velvet,53.74,1,In stock,All Books,5642.70
2,Soumission,50.10,1,In stock,All Books,5260.50
3,Sharp Objects,47.82,4,In stock,All Books,5021.10
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,All Books,5694.15

CONVERTS BOOLEAN

In [112]:
df["availability"].unique()

<StringArray>
['In stock']
Length: 1, dtype: str

In [113]:
df["availability"] = (
    df["availability"]
    .str.strip()
    .str.contains("in stock", case = False)
)

In [114]:
print(df["availability"].head())

0    True
1    True
2    True
3    True
4    True
Name: availability, dtype: bool

In [115]:
df.dtypes

title               str
price_gbp       float64
star_rating       int64
availability       bool
category            str
price_inr       float64
dtype: object

In [120]:
df.rename(columns = {"availability" : "in_stock"}, inplace = True)

In [123]:
df.rename(columns = {"star_rating" : "rating"} , inplace = True)

SAVE THE CLEANED DATA SET

In [124]:
df.head()

,title,price_gbp,rating,in_stock,category,price_inr
0,A Light in the Attic,51.77,3,True,All Books,5435.85
1,Tipping the Velvet,53.74,1,True,All Books,5642.70
2,Soumission,50.10,1,True,All Books,5260.50
3,Sharp Objects,47.82,4,True,All Books,5021.10
4,Sapiens: A Brief History of Humankind,54.23,5,True,All Books,5694.15

In [125]:
df.to_csv("C:\\Users\\mundl\\OneDrive\\Documents\\data_pipeline\\data\\cleaned_books.csv", index = False)